version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet_db
    networks:
      - app-network

  studio:
    build:
      context: .
      dockerfile: ./docker/nest/Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - nest-api
    networks:
      - app-network
    environment:
      - TZ=Asia/Tokyo
    command: pnpm prisma studio --port 5555 --hostname 0.0.0.0

  nest-api:
    build:
      context: .
      dockerfile: ./docker/nest/Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
